---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations: {}
  name: minio-access-secrets
stringData:
  minioSecret: demosecretkey
  minioAccessKey: demoaccesskey
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-config-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-server
spec:
  type: NodePort
  selector:
    app: minio-server
  ports:
    - name: web
      port: 80
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-server
spec:
  selector:
    matchLabels:
      app: minio-server
  template:
    metadata:
      labels:
        app: minio-server
    spec:
      containers:
        - name: minio
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secrets
                  key: minioAccessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secrets
                  key: minioSecret
          image: minio/minio
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              protocol: TCP
              name: web
          volumeMounts:
            - name: home
              mountPath: /data
            - name: config
              mountPath: /root/.minio
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: home-claim
        - name: config
          persistentVolumeClaim:
            claimName: minio-config-claim
