apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/ryanzhang/openshift-demo-application
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkus-image
spec:
  type: image
  params: 
  - name: url
    value: "image-registry.openshift-image-registry.svc:5000/bootcamp-serverless/quarkus-app:v0.1"