apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: kn-svc-deploy
spec:
  params:
  - name: mavenMirrorUrl
    description: the maven mirror
    default: http://nexus.default.svc:8081/nexus/content/groups/public
  resources: 
  - name: appSource
    type: git
  - name: appImage
    type: image
  tasks: 
   - name: build-java-app
     taskRef:
       name: build-app
     params:
      - name: contextDir
        value: java/quarkus
      - name: mavenMirrorUrl
        value: "$(params.mavenMirrorUrl)"
     resources:
      inputs:
        - name: source
          resource: appSource
      outputs:
        - name: builtImage
          resource: appImage
   - name: deploy-kn-service
     taskRef:
       name: kn-deploy
     runAfter:
      - build-java-app
     resources:
      inputs:
        - name: image
          resource: appImage
     params:
      - name: ARGS
        value:
        - "service"
        - "create"
        - "greeter"
        - "--force"
        - "--image=$(inputs.resources.image.url)"